### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by listentothefrog** [listentothefrog/Vibes#1]
- [ ] Sign up With Google Auth
- [ ] Create a room by default when user signs up 
- [ ] Real time chat with Database 
- [ ] Shareable links 
- [ ] Better Ui 
- [ ] Vibes Mobile 
- [ ] Tutorials for new users
